version: "3"
networks:
  stack: {}
volumes:
  postgres-data: {}
  pgadmin-data: {}
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: pocketlaw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d metrics -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6
    networks:
      - stack
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    restart: on-failure
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    networks:
      - stack
    environment:
      DATABASE_URL: postgres://postgres:docker@postgres:5432/pocketlaw
      NODE_ENV: development
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

